
# D:/Media/Work/Third Year 2015/CSC3003S/Compilers 1/Compilers1 Project\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'B4D70A31F88587BA854DDCF46F13A0FA'
    
_lr_action_items = {'ID':([0,3,7,10,11,12,13,],[2,9,9,9,9,9,9,]),'PLUS':([4,5,6,8,9,14,15,16,17,18,19,],[-4,-7,13,-9,-10,13,-6,-5,-3,-2,-8,]),'DIVIDE':([4,5,8,9,15,16,17,18,19,],[10,-7,-9,-10,-6,-5,10,10,-8,]),'TIMES':([4,5,8,9,15,16,17,18,19,],[11,-7,-9,-10,-6,-5,11,11,-8,]),'RPAREN':([4,5,8,9,14,15,16,17,18,19,],[-4,-7,-9,-10,19,-6,-5,-3,-2,-8,]),'MINUS':([4,5,6,8,9,14,15,16,17,18,19,],[-4,-7,12,-9,-10,12,-6,-5,-3,-2,-8,]),'FLOAT_LITERAL':([3,7,10,11,12,13,],[8,8,8,8,8,8,]),'LPAREN':([3,7,10,11,12,13,],[7,7,7,7,7,7,]),'EQUAL':([2,],[3,]),'$end':([1,4,5,6,8,9,15,16,17,18,19,],[0,-4,-7,-1,-9,-10,-6,-5,-3,-2,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([3,7,],[6,14,]),'term':([3,7,12,13,],[4,4,17,18,]),'statement':([0,],[1,]),'factor':([3,7,10,11,12,13,],[5,5,15,16,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID EQUAL expression','statement',3,'p_statement_id','parse_ula.py',12),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parse_ula.py',16),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parse_ula.py',20),
  ('expression -> term','expression',1,'p_expression_term','parse_ula.py',24),
  ('term -> term TIMES factor','term',3,'p_term_times','parse_ula.py',28),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parse_ula.py',32),
  ('term -> factor','term',1,'p_term_factor','parse_ula.py',36),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parse_ula.py',40),
  ('factor -> FLOAT_LITERAL','factor',1,'p_factor_float','parse_ula.py',44),
  ('factor -> ID','factor',1,'p_factor_id','parse_ula.py',48),
]
